# Generated by Django 4.2.19 on 2025-03-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CL", "Клиент"),
                    ("CK", "Повар"),
                    ("WT", "Официант"),
                    ("SU", "Админ"),
                ],
                default="CL",
                max_length=2,
            ),
        ),
    ]
