# Generated by Django 4.2.19 on 2025-02-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEND', 'в ожидании'), ('INPR', 'в процессе'), ('COMP', 'завершен'), ('CANC', 'отменен')], default='PEND', max_length=4),
        ),
    ]
