# Generated by Django 4.2.19 on 2025-03-01 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_meal_description_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEND', 'в ожидании'), ('INPR', 'в процессе'), ('COMP', 'завершен'), ('CANC', 'отменен'), ('PAID', 'оплачен')], default='PEND', max_length=4),
        ),
    ]
